configurations = {
    'default': dict(
        SEED = 1337, 
        TRAIN_DATA_ROOT = '/datasets/face/ms1mv2', 
        EVAL_DATA_ROOT = 'eval_data', 
        IJB_DATA_ROOT = '/datasets/face/IJB_release',
        EVAL_TARGETS = ['lfw'], 
        EXP_NAME = 'my_exp',
        BACKBONE_RESUME_ROOT = "", 
        HEAD_RESUME_ROOT = "",
        DIFF_RESUME_ROOT = "", 
        BACKBONE_NAME = 'IR_100', 
        HEAD_NAME = "ArcFace", 
        LOSS_NAME = 'Softmax',
        INPUT_SIZE = [112, 112], 
        EMBEDDING_SIZE = 512, 
        BATCH_SIZE = 512, 
        LR = 0.1,
        NH = 1,
        NE = 7,
        K = 64, 
        NP = 500,
        WC = 0.5,
        WD = 1.0,
        END_EPOCH = 24, 
        WEIGHT_DECAY = 5e-4, 
        MOMENTUM = 0.9,
        STAGES = [10, 18, 22], 
        NUM_WORKERS = 4,
    ),

    'pretrain': dict(
        SEED = 1337, 
        TRAIN_DATA_ROOT = '/datasets/face/ms1mv2', 
        EVAL_DATA_ROOT = 'eval_data', 
        IJB_DATA_ROOT = '/datasets/face/IJB_release',
        EVAL_TARGETS = ['lfw'], 
        EXP_NAME = 'pretrain',
        BACKBONE_NAME = 'IR_100', 
        HEAD_NAME = "ArcFace", 
        LOSS_NAME = 'Softmax',
        INPUT_SIZE = [112, 112], 
        EMBEDDING_SIZE = 512, 
        BATCH_SIZE = 512, 
        LR = 0.1, 
        END_EPOCH = 4, 
        WEIGHT_DECAY = 5e-4, 
        MOMENTUM = 0.9,
        STAGES = [10, 18, 22],
        NUM_WORKERS = 4,
    ),

}
